version: '3'

services:
  # flask:
  #   container_name: flaskapp
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - APP_NAME=FlaskApp
  #   expose:
  #     - 5000
  #   depends_on:
  #     - psql
  #   volumes:
  #     - .:/app

  psql:
    container_name: psql-snpj
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dino
      - POSTGRES_PASSWORD=dinopwd
      - POSTGRES_DB=dino
    volumes:
      - /senior_project/postgres_data:/var/lib/postgresql/data